name: Build and Push Docker Image on Release

permissions: write-all
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Prepare Image name
      env: 
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
      run: |
        echo "DOCKER_IMAGE=ghcr.io/$OWNER/$REPO" >> $GITHUB_ENV

    - name: Build Docker image
      env:   
        TAG_NAME: ${{ github.event.release.tag_name }} 
      run: |
        docker build -t $DOCKER_IMAGE:$TAG_NAME .
        docker tag $DOCKER_IMAGE:$TAG_NAME $DOCKER_IMAGE:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      env:
        TAG_NAME: ${{ github.event.release.tag_name }} 
      run: |
        docker push $DOCKER_IMAGE:$TAG_NAME
        docker push $DOCKER_IMAGE:latest